//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Current_new_info.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_class
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Describtion { get; set; }
        public string Category { get; set; }
        public string Publishdate { get; set; }
    }
}
