//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_LAb_task.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Deptid { get; set; }
        public string Deptname { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
