//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_SSC.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Or_id { get; set; }
        public Nullable<int> O_Id { get; set; }
        public Nullable<int> Id { get; set; }
    
        public virtual Order_product Order_product { get; set; }
        public virtual Product Product { get; set; }
    }
}
